---
# no sub directory for ansible playbooks to find roles under roles/ directory

- import_playbook: upgrade_os.yml

- import_playbook: config_dev_repos.yml

- import_playbook: install_pf.yml
    
- import_playbook: env_vars.yml
  
- import_playbook: go_env.yml
  when: lookup("env", "GOLANG_UNIT_TESTS") == 'yes'
  
- import_playbook: winservers.yml
  
- import_playbook: cumulus.yml
  
- import_playbook: nodes.yml
  
- import_playbook: wireless.yml
  
- import_playbook: utils.yml

