---
- name: Configure Wireless Linux
  hosts: wireless
  become: true
  gather_facts: true
  
  collections:
    - inverse_inc.wireless

  pre_tasks:
  - name: wait for SSH available before provisioning
    wait_for_connection:

  roles:
    - role: hostapd
      # to avoid a failure when PF_VM_NAME is not defined
      when: lookup("env", "PF_VM_NAME")
    - role: wpasupplicant
